// <auto-generated />
namespace RGC2020MVC.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBulkInsertCompetitionCompetitionTypesScoreUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBulkInsertCompetitionCompetitionTypesScoreUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201612172107467_AddBulkInsertCompetitionCompetitionTypesScoreUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
